from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ferelight.models.base_model import Model
from ferelight import util


class ObjectinfosPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, objectids=None):  # noqa: E501
        """ObjectinfosPostRequest - a model defined in OpenAPI

        :param objectids: The objectids of this ObjectinfosPostRequest.  # noqa: E501
        :type objectids: List[str]
        """
        self.openapi_types = {
            'objectids': List[str]
        }

        self.attribute_map = {
            'objectids': 'objectids'
        }

        self._objectids = objectids

    @classmethod
    def from_dict(cls, dikt) -> 'ObjectinfosPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _objectinfos_post_request of this ObjectinfosPostRequest.  # noqa: E501
        :rtype: ObjectinfosPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def objectids(self) -> List[str]:
        """Gets the objectids of this ObjectinfosPostRequest.

        The unique identifiers of the objects.  # noqa: E501

        :return: The objectids of this ObjectinfosPostRequest.
        :rtype: List[str]
        """
        return self._objectids

    @objectids.setter
    def objectids(self, objectids: List[str]):
        """Sets the objectids of this ObjectinfosPostRequest.

        The unique identifiers of the objects.  # noqa: E501

        :param objectids: The objectids of this ObjectinfosPostRequest.
        :type objectids: List[str]
        """

        self._objectids = objectids
