from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ferelight.models.base_model import Model
from ferelight import util


class QueryPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, similaritytext=None, ocrtext=None):  # noqa: E501
        """QueryPostRequest - a model defined in OpenAPI

        :param similaritytext: The similaritytext of this QueryPostRequest.  # noqa: E501
        :type similaritytext: str
        :param ocrtext: The ocrtext of this QueryPostRequest.  # noqa: E501
        :type ocrtext: str
        """
        self.openapi_types = {
            'similaritytext': str,
            'ocrtext': str
        }

        self.attribute_map = {
            'similaritytext': 'similaritytext',
            'ocrtext': 'ocrtext'
        }

        self._similaritytext = similaritytext
        self._ocrtext = ocrtext

    @classmethod
    def from_dict(cls, dikt) -> 'QueryPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _query_post_request of this QueryPostRequest.  # noqa: E501
        :rtype: QueryPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def similaritytext(self) -> str:
        """Gets the similaritytext of this QueryPostRequest.

        The similarity text.  # noqa: E501

        :return: The similaritytext of this QueryPostRequest.
        :rtype: str
        """
        return self._similaritytext

    @similaritytext.setter
    def similaritytext(self, similaritytext: str):
        """Sets the similaritytext of this QueryPostRequest.

        The similarity text.  # noqa: E501

        :param similaritytext: The similaritytext of this QueryPostRequest.
        :type similaritytext: str
        """

        self._similaritytext = similaritytext

    @property
    def ocrtext(self) -> str:
        """Gets the ocrtext of this QueryPostRequest.

        The OCR text.  # noqa: E501

        :return: The ocrtext of this QueryPostRequest.
        :rtype: str
        """
        return self._ocrtext

    @ocrtext.setter
    def ocrtext(self, ocrtext: str):
        """Sets the ocrtext of this QueryPostRequest.

        The OCR text.  # noqa: E501

        :param ocrtext: The ocrtext of this QueryPostRequest.
        :type ocrtext: str
        """

        self._ocrtext = ocrtext
